
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdqkbqbxjejkxeoldvue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkcWticWJ4amVqa3hlb2xkdnVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzMxNDksImV4cCI6MjA2MTU0OTE0OX0.eQHjClAihH5CvqkmZKYy6PJfLjdKyVauBBH8cguPCR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Helper function to get storage URLs
export const getStorageUrl = (bucketName: string, fileName: string): string => {
  return `${SUPABASE_URL}/storage/v1/object/public/${bucketName}/${fileName}`;
};

// Helper for thumbnail URLs
export const getThumbnailUrl = (fileId: string): string => {
  return `${SUPABASE_URL}/storage/v1/object/public/thumbnails/${fileId}.jpg`;
};
